### ISSUE TITLE
NoMethodError: undefined method `createMsgChannel' for nil:NilClass

### ISSUE THREAD

**Issue by liveh2o** [abrandoned/protobuf-nats#32]
Occasionally, we're seeing this error when starting up an RPC process:

```
NoMethodError: undefined method `createMsgChannel' for nil:NilClass
/srv/kirby/shared/bundle/jruby/2.3.0/gems/protobuf-nats-0.7.0/lib/protobuf/nats/jnats.rb:103:in `subscribe'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/protobuf-nats-0.7.0/lib/protobuf/nats/client.rb:135:in `nats_request_with_two_responses'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/protobuf-nats-0.7.0/lib/protobuf/nats/client.rb:79:in `block in send_request'
org/jruby/RubyKernel.java:1298:in `loop'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/protobuf-nats-0.7.0/lib/protobuf/nats/client.rb:76:in `send_request'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/protobuf-3.8.1/lib/protobuf/rpc/client.rb:129:in `method_missing'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/active_remote-3.1.1/lib/active_remote/rpc_adapters/protobuf_adapter.rb:22:in `execute'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/active_remote-3.1.1/lib/active_remote/search.rb:91:in `search'
/srv/kirby/releases/20171101175003/lib/kirby/accounts_processor.rb:153:in `existing_users'
/srv/kirby/releases/20171101175003/lib/kirby/accounts_processor.rb:27:in `block in process'
org/jruby/RubyArray.java:2486:in `map'
/srv/kirby/releases/20171101175003/lib/kirby/accounts_processor.rb:26:in `process'
/srv/kirby/releases/20171101175003/app/workers/accounts_worker.rb:13:in `perform'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:199:in `execute_job'
/srv/kirby/shared/bundle/jruby/2.3.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:170:in `block in process'
...
```

Usually, a restart "fixes" it. Not really sure what's going on beyond that.

**Comment by film42** [comment]
😢 I'll do a deep dive today to figure out what's going on. Thanks @liveh2o !
